export const SEARCH_PLAYERS = 'SEARCH_PLAYERS';
export const PLAYERS_LOADING = 'PLAYERS_LOADING';

export const GET_MATCHES = 'GET_MATCHES';
export const MATCHES_LOADING = 'MATCHES_LOADING';

export const VIEW_PLAYER = 'VIEW_PLAYER';
export const VIEW_PLAYERS_LOADING = 'VIEW_PLAYERS_LOADING';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_SEARCH_HISTORY = 'GET_SEARCH_HISTORY';
export const SEARCH_HISTORY_LOADING = 'SEARCH_HISTORY_LOADING';
export const DELETE_SEARCH_HISTORY = 'DELETE_SEARCH_HISTORY';

export const GET_RANDOM_JOKE = "GET_RANDOM_JOKE";

export const UPDATE_PASSWORD_LOADING = "UPDATE_PASSWORD_LOADING";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";